mod champernownes_constant;
mod collatz;
mod consecutive_prime_sum;
mod digit_replacement;
mod fibonacci;
mod hexagonal_numbers;
mod pandigital_numbers;
mod pentagonal_numbers;
mod primes;
mod pythagorus;
mod quadratic_formula;
mod spiral_diagonal_numbers;
mod triangle_numbers;

pub use champernownes_constant::ChampernownesConstant;
pub use collatz::Collatz;
pub use consecutive_prime_sum::*;
pub use digit_replacement::*;
pub use fibonacci::Fibonacci;
pub use hexagonal_numbers::HexagonalNumberGenerator;
pub use pandigital_numbers::pandigital_numbers_of_length;
pub use pentagonal_numbers::PentagonalNumberGenerator;
pub use primes::Primes;
pub use pythagorus::PythagoreanTriplets;
pub use quadratic_formula::QuadraticFormula;
pub use spiral_diagonal_numbers::SpiralDiagonalNumbers;
pub use triangle_numbers::TriangleNumbers;
