/// The sequence of triangle numbers is generated by adding the
/// natural numbers. So the 7th triangle number would be
/// 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
pub struct TriangleNumbers {
    sum: u128,
    index: u128,
}

impl TriangleNumbers {
    /// starts a new Triangle Numbers iterator
    pub fn new() -> Self {
        Self { sum: 0, index: 0 }
    }
}

impl Iterator for TriangleNumbers {
    type Item = u128;

    fn next(&mut self) -> Option<Self::Item> {
        self.index += 1;
        self.sum += self.index;
        return Some(self.sum);
    }
}

#[cfg(test)]
mod tests {
    use super::TriangleNumbers;

    #[test]
    fn test_triangle_numbers() {
        assert_eq!(28, TriangleNumbers::new().take(7).last().unwrap())
    }
}
